name: Go CI

on:
  push:
    tags:
      - 'v*' # This will trigger the workflow on pushing tags that start with 'v'

permissions:
  contents: write # This line gives the workflow permission to create releases

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goarch: [amd64, arm64]
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Check out code
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      env:
        GOARCH: ${{ matrix.goarch }}
      run: go build -v -o ${{ github.event.repository.name }}-${{ matrix.goarch }} .

    - name: Test
      run: go test -v .

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.repository.name }}-${{ matrix.goarch }}
        path: ${{ github.event.repository.name }}-${{ matrix.goarch }}

  release:
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifacts
        uses: actions/download-artifact@v2

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ${{ github.event.repository.name }}-amd64/${{ github.event.repository.name }}-amd64
            ${{ github.event.repository.name }}-arm64/${{ github.event.repository.name }}-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
